# Generated by Django 5.2.8 on 2025-12-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bus_number', models.CharField(max_length=20, unique=True)),
                ('total_seats', models.PositiveIntegerField()),
            ],
        ),
    ]
